id: A4BB33226
title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
  the Great Omniscient Jonangpa from Afar'
type: translation
pechas:
- IAFF18183
- IE5FA6009
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:48.635747
  last_modified_at: 2023-01-04 11:44:48.635758
  collections:
  - Dolpopa Sherab Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  IAFF18183/9252: 780A
  IE5FA6009/8F48: 780A
